{
 "title": "Flink Dashboard",
 "description": "Flink dashboard using the Prometheus exporter. https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/metrics.html#prometheus-orgapacheflinkmetricsprometheusprometheusreporter ",
 "tags": [ "flink" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "JobManager CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TaskManager CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JobManager Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TaskManager Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Taskslots available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "Taskslots total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal"
    }
   ]
  },
  {
   "title": "# of TaskManagers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers"
    }
   ]
  },
  {
   "title": "# of Running Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs"
    }
   ]
  },
  {
   "title": "TaskManagers Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time",
     "legendFormat": "{{instance}} Young Gen Time"
    },
    {
     "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time",
     "legendFormat": "{{instance}} Old Gen Time"
    }
   ]
  },
  {
   "title": "JobManager Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_GarbageCollector_Copy_Time",
     "legendFormat": "{{instance}} GC Copy Time"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time",
     "legendFormat": "{{instance}} GC MarkSweep Time"
    }
   ]
  }
 ]
}