server:
  port: 8084

spring:
  application:
    name: reports-service

  config:
    import: "optional:file:.env[.properties],optional:file:../.env[.properties]"

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:cdia}
    username: ${CDIA_APP_DB_USER:cdia_app}
    password: ${CDIA_APP_DB_PASSWORD:change_me_app}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:elastic}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:test}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      app: ${spring.application.name}
