server:
  port: 8085

spring:
  application:
    name: search-service
  
  config:
    import: "optional:file:.env[.properties],optional:file:../.env[.properties]"

  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:elastic}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:test}
    connection-timeout: 5s
    socket-timeout: 30s

logging:
  level:
    org.springframework.data.elasticsearch: INFO
    co.elastic.clients: WARN
    org.springframework.data.elasticsearch.core: DEBUG
    org.springframework.data.elasticsearch.repository: DEBUG
